library(tidyverse)
library(dplyr)

TR<-read.csv("C:/users/chris/Documents/GitHub/YT-D/Week 1/0711/train.csv")
H1<-read.csv("C:/users/chris/Documents/GitHub/YT-D/Week 1/0711/TaipeiHotel_1_Jan.csv")
H2<-read.csv("C:/users/chris/Documents/GitHub/YT-D/Week 1/0711/TaipeiHotel_2_Feb.csv")
H3<-read.csv("C:/users/chris/Documents/GitHub/YT-D/Week 1/0711/TaipeiHotel_3_Mar.csv")
H4<-read.csv("C:/users/chris/Documents/GitHub/YT-D/Week 1/0711/TaipeiHotel_4_Apr.csv")
H5<-read.csv("C:/users/chris/Documents/GitHub/YT-D/Week 1/0711/TaipeiHotel_5_May.csv")
H6<-read.csv("C:/users/chris/Documents/GitHub/YT-D/Week 1/0711/TaipeiHotel_6_Jun.csv")


TP_TR<-filter(TR,82 < TKT_BEG,TKT_BEG < 106)
TR_Jan<-filter(TP_TR,str_detect(BOARD_DATE,"201801"))
TR_Feb<-filter(TP_TR,str_detect(BOARD_DATE,"201802"))
TR_Mar<-filter(TP_TR,str_detect(BOARD_DATE,"201803"))
TR_Apr<-filter(TP_TR,str_detect(BOARD_DATE,"201804"))
TR_May<-filter(TP_TR,str_detect(BOARD_DATE,"201805"))
TR_Jun<-filter(TP_TR,str_detect(BOARD_DATE,"201806"))

TR_JanO<-select(TR_Jan,out)
TR_JanO_Sum<-sum(TR_JanO)
TR_FebO<-select(TR_Feb,out)
TR_FebO_Sum<-sum(TR_FebO)
TR_MarO<-select(TR_Mar,out)
TR_MarO_Sum<-sum(TR_MarO)
TR_AprO<-select(TR_Apr,out)
TR_AprO_Sum<-sum(TR_AprO)
TR_MayO<-select(TR_May,out)
TR_MayO_Sum<-sum(TR_MayO)
TR_JunO<-select(TR_Jun,out)
TR_JunO_Sum<-sum(TR_JunO)

H1_low<- filter(H1, Average.Room.Rate < 3000)
H1_mid<- filter(H1, Average.Room.Rate > 3000, Average.Room.Rate < 4000)
H1_high<- filter(H1, Average.Room.Rate > 4000)
H2_low<- filter(H2, Average.Room.Rate < 3000)
H2_mid<- filter(H2, Average.Room.Rate > 3000, Average.Room.Rate < 4000)
H2_high<- filter(H2, Average.Room.Rate > 4000)
H3_low<- filter(H3, Average.Room.Rate < 3000)
H3_mid<- filter(H3, Average.Room.Rate > 3000, Average.Room.Rate < 4000)
H3_high<- filter(H3, Average.Room.Rate > 4000)
H4_low<- filter(H4, Average.Room.Rate < 3000)
H4_mid<- filter(H4, Average.Room.Rate > 3000, Average.Room.Rate < 4000)
H4_high<- filter(H4, Average.Room.Rate > 4000)
H5_low<- filter(H5, Average.Room.Rate < 3000)
H5_mid<- filter(H5, Average.Room.Rate > 3000, Average.Room.Rate < 4000)
H5_high<- filter(H5, Average.Room.Rate > 4000)
H6_low<- filter(H6, Average.Room.Rate < 3000)
H6_mid<- filter(H6, Average.Room.Rate > 3000, Average.Room.Rate < 4000)
H6_high<- filter(H6, Average.Room.Rate > 4000)

H1_low_Occ<-select(H1_low,No..of.Rooms.Occupied)
H1_low_num<-sum(H1_low_Occ)
H1_mid_Occ<-select(H1_mid,No..of.Rooms.Occupied)
H1_mid_num<-sum(H1_mid_Occ)
H1_high_Occ<-select(H1_high,No..of.Rooms.Occupied)
H1_high_num<-sum(H1_high_Occ)
H2_low_Occ<-select(H2_low,No..of.Rooms.Occupied)
H2_low_num<-sum(H2_low_Occ)
H2_mid_Occ<-select(H2_mid,No..of.Rooms.Occupied)
H2_mid_num<-sum(H2_mid_Occ)
H2_high_Occ<-select(H2_high,No..of.Rooms.Occupied)
H2_high_num<-sum(H2_high_Occ)
H3_low_Occ<-select(H3_low,No..of.Rooms.Occupied)
H3_low_num<-sum(H3_low_Occ)
H3_mid_Occ<-select(H3_mid,No..of.Rooms.Occupied)
H3_mid_num<-sum(H3_mid_Occ)
H3_high_Occ<-select(H3_high,No..of.Rooms.Occupied)
H3_high_num<-sum(H3_high_Occ)
H4_low_Occ<-select(H4_low,No..of.Rooms.Occupied)
H4_low_num<-sum(H4_low_Occ)
H4_mid_Occ<-select(H4_mid,No..of.Rooms.Occupied)
H4_mid_num<-sum(H4_mid_Occ)
H4_high_Occ<-select(H4_high,No..of.Rooms.Occupied)
H4_high_num<-sum(H4_high_Occ)
H5_low_Occ<-select(H5_low,No..of.Rooms.Occupied)
H5_low_num<-sum(H5_low_Occ)
H5_mid_Occ<-select(H5_mid,No..of.Rooms.Occupied)
H5_mid_num<-sum(H5_mid_Occ)
H5_high_Occ<-select(H5_high,No..of.Rooms.Occupied)
H5_high_num<-sum(H5_high_Occ)
H6_low_Occ<-select(H6_low,No..of.Rooms.Occupied)
H6_low_num<-sum(H6_low_Occ)
H6_mid_Occ<-select(H6_mid,No..of.Rooms.Occupied)
H6_mid_num<-sum(H6_mid_Occ)
H6_high_Occ<-select(H6_high,No..of.Rooms.Occupied)
H6_high_num<-sum(H6_high_Occ)
