library(tidyverse)
library(dplyr)

TR<-read.csv("C:/users/chris/Desktop/YT-D/Week 1/0711/train.csv")
H1<-read.csv("C:/users/chris/Desktop/YT-D/Week 1/0711/TaipeiHotel_1_Jan.csv")
H2<-read.csv("C:/users/chris/Desktop/YT-D/Week 1/0711/TaipeiHotel_2_Feb.csv")
H3<-read.csv("C:/users/chris/Desktop/YT-D/Week 1/0711/TaipeiHotel_3_Mar.csv")
H4<-read.csv("C:/users/chris/Desktop/YT-D/Week 1/0711/TaipeiHotel_4_Apr.csv")
H5<-read.csv("C:/users/chris/Desktop/YT-D/Week 1/0711/TaipeiHotel_5_May.csv")
H6<-read.csv("C:/users/chris/Desktop/YT-D/Week 1/0711/TaipeiHotel_6_Jun.csv")

#導入套件和檔案

TR_TP<-filter(TR,82 < TKT_BEG & TKT_BEG < 106)
mon=substring(TR_TP$BOARD_DATE,first = 1,last = 6)
TR_TP_M<-mutate(TR_TP,Month=mon)
head(TR_TP_M)
TR_Fin<-group_by(TR_TP_M,Month)%>%
  summarise(out_sum=sum(out))
head(TR_Fin)

#台北地區鐵路出站人次

objects(H1)

H1_low<- filter(H1, Average.Room.Rate < 3000)
H1_mid<- filter(H1, Average.Room.Rate > 3000, Average.Room.Rate < 4000)
H1_high<- filter(H1, Average.Room.Rate > 4000)
H2_low<- filter(H2, Average.Room.Rate < 3000)
H2_mid<- filter(H2, Average.Room.Rate > 3000, Average.Room.Rate < 4000)
H2_high<- filter(H2, Average.Room.Rate > 4000)
H3_low<- filter(H3, Average.Room.Rate < 3000)
H3_mid<- filter(H3, Average.Room.Rate > 3000, Average.Room.Rate < 4000)
H3_high<- filter(H3, Average.Room.Rate > 4000)
H4_low<- filter(H4, Average.Room.Rate < 3000)
H4_mid<- filter(H4, Average.Room.Rate > 3000, Average.Room.Rate < 4000)
H4_high<- filter(H4, Average.Room.Rate > 4000)
H5_low<- filter(H5, Average.Room.Rate < 3000)
H5_mid<- filter(H5, Average.Room.Rate > 3000, Average.Room.Rate < 4000)
H5_high<- filter(H5, Average.Room.Rate > 4000)
H6_low<- filter(H6, Average.Room.Rate < 3000)
H6_mid<- filter(H6, Average.Room.Rate > 3000, Average.Room.Rate < 4000)
H6_high<- filter(H6, Average.Room.Rate > 4000)
str(H1_low)

H1_low_num<-sum(select(H1_low,No..of.Rooms.Occupied))
H1_mid_num<-sum(select(H1_mid,No..of.Rooms.Occupied))
H1_high_num<-sum(select(H1_high,No..of.Rooms.Occupied))
H2_low_num<-sum(select(H2_low,No..of.Rooms.Occupied))
H2_mid_num<-sum(select(H2_mid,No..of.Rooms.Occupied))
H2_high_num<-sum(select(H2_high,No..of.Rooms.Occupied))
H3_low_num<-sum(select(H3_low,No..of.Rooms.Occupied))
H3_mid_num<-sum(select(H3_mid,No..of.Rooms.Occupied))
H3_high_num<-sum(select(H3_high,No..of.Rooms.Occupied))
H4_low_num<-sum(select(H4_low,No..of.Rooms.Occupied))
H4_mid_num<-sum(select(H4_mid,No..of.Rooms.Occupied))
H4_high_num<-sum(select(H4_high,No..of.Rooms.Occupied))
H5_low_num<-sum(select(H5_low,No..of.Rooms.Occupied))
H5_mid_num<-sum(select(H5_mid,No..of.Rooms.Occupied))
H5_high_num<-sum(select(H5_high,No..of.Rooms.Occupied))
H6_low_num<-sum(select(H6_low,No..of.Rooms.Occupied))
H6_mid_num<-sum(select(H6_mid,No..of.Rooms.Occupied))
H6_high_num<-sum(select(H6_high,No..of.Rooms.Occupied))
