# HW3:文字探勘
## 政大 國貿二 鄧羽彤    
  
    
### 導入套件與檔案  
```{r results ='hide',message =FALSE,warning=FALSE}
library(rvest)
library(jiebaRD)
library(jiebaR)
library(NLP)
library(tm)
library(tmcn)
library(RColorBrewer)
library(wordcloud)
library(dplyr)
library(ggplot2)
library(knitr)
```

### 讀取網站文字  
```{r}
url<-read_html("https://www.dcard.tw/f/food/p/224587575")

article<-html_nodes(url,".CommentEntry_content_1ATrw1 div , .Post_content_NKEl9d div , .Post_title_2O-1el")
text<-html_text(article)
print(text)
```

### 斷詞  
```{r}
cutter=worker()
words<-cutter[(text)]
print(words)

words<-gsub("[A-Za-z0-9]","",words)
not<-which(words=="")
words<-words[-not]
print(words)
```

### 文字雲
```{r}
freq<-table(words)
print(freq)
head(sort(freq, decreasing=T))
wordcloud(names(freq),freq,min.freq=5,max.words=50)
```

### 長條圖  
```{r}
freq_2<-t(t(freq))
print(freq_2)
data<-data.frame(freq_2)
Bar<-ggplot(data=data,aes(x=words,y=Freq,fill=Freq)) +
  geom_bar(stat="identity")
print(Bar)
```

### TF-IDF
```{r}
words_tm<-VCorpus(VectorSource(words))
stopwords<-c(stopwordsCN(),"啊啊啊","哈哈哈")
words_tm<-tm_map(words_tm,removeWords,stopwords)
words_tm<-tm_map(words_tm,removePunctuation)

TDM<-TermDocumentMatrix(words_tm)
inspect(TDM)

TFIDF<-as.matrix(TDM)
```